"""FlyWire FAFB v783 source: the Codex download bundle -> schema v1 tables.

Raw files come from the Codex "Flywire_raw_data" bundle (see
:mod:`connexplorer.ingest.download`). Only ``neurons.csv.gz``,
``consolidated_cell_types.csv(.gz)`` and the Princeton synapse table are
required; the rest enrich ``cells``/``types``/``columns`` when present.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Iterator

import polars as pl
import pyarrow as pa
import pyarrow.csv as pcsv

from connexplorer.ingest.base import RawDir, RawFile, Source, _majority, nullify_sentinels

# Literature neurotransmitter overrides applied on top of the per-type majority
# of the FlyWire prediction. Inherited verbatim from cex
# (``cex.dataset.schema.TYPE_NEUROTRANSMITTER_GT``); the FlyWire predictor has
# no histamine class, and these Dm types and T1 were consistently mispredicted.
# Authors: add a citation per entry when extending this table, and bump
# NT_OVERRIDES_VERSION so the manifest changes.
NT_OVERRIDES: dict[str, str] = {
    "R1-6": "HIS",  # photoreceptors are histaminergic; predictor lacks HIS
    "R7": "HIS",
    "R8": "HIS",
    "Dm1": "GLUT",
    "Dm6": "GLUT",
    "Dm8": "GLUT",
    "Dm9": "GLUT",
    "Dm12": "GLUT",
    "Dm16": "GLUT",
    "Dm17": "GLUT",
    "Dm19": "GLUT",
    "Dm20": "GLUT",
    "T1": "GLUT",
}
NT_OVERRIDES_VERSION = "flywire-cex13-2026-09"

RAW_FILES: dict[str, RawFile] = {
    "neurons": RawFile("neurons", "neurons.csv.gz", description="cell universe, group, NT prediction + scores"),
    "cell_types": RawFile(
        "cell_types", "consolidated_cell_types.csv.gz", alternatives=("consolidated_cell_types.csv",),
        description="primary_type and additional types",
    ),
    "synapses": RawFile("synapses", "fafb_v783_princeton_synapse_table.csv.gz", description="80M synapses with nm coordinates"),
    "classification": RawFile(
        "classification", "classification.csv", required=False, alternatives=("classification.csv.gz",),
        description="flow, super_class, class, sub_class, hemilineage, side, nerve",
    ),
    "names": RawFile("names", "names.csv.gz", required=False, description="autogenerated cell names"),
    "connectivity_tags": RawFile("connectivity_tags", "connectivity_tags.csv.gz", required=False),
    "visual_types": RawFile(
        "visual_types", "visual_neuron_types.csv", required=False, alternatives=("visual_neuron_types.csv.gz",),
        description="optic-lobe type family / subsystem / category",
    ),
    "columns": RawFile("columns", "column_assignment.csv.gz", required=False, description="hex column coordinates"),
    "connections": RawFile(
        "connections", "connections_princeton_no_threshold.csv.gz", required=False, read=False,
        description="vendor pair table; not used (autapses missing, one cell absent)",
    ),
    "skeletons": RawFile("skeletons", "sk_lod1_783_healed.zip", required=False, read=False, description="SWC skeletons, microns"),
}

_SYNAPSE_COLUMNS = ["ctr_x", "ctr_y", "ctr_z", "neuropil"]
_ROOT_ID_DIGITS = 18


def _csv(path: Path, **kw) -> pl.DataFrame:
    return pl.read_csv(path, schema_overrides={"root_id": pl.Int64}, **kw)


class FlyWireSource(Source):
    name = "flywire"
    raw_files = RAW_FILES
    nt_overrides = NT_OVERRIDES
    nt_overrides_version = NT_OVERRIDES_VERSION
    type_summary_columns = ("flow", "superclass", "class", "subclass", "hemilineage", "nerve", "group")

    def __init__(self, version: str = "783", block_size: int = 64 << 20):
        self.version = version
        self.block_size = block_size

    # ---- cells ------------------------------------------------------------

    def cells(self, raw: RawDir) -> pl.DataFrame:
        neurons = _csv(raw.path("neurons")).rename({"nt_type": "nt", "nt_type_score": "nt_score"})
        types = _csv(raw.path("cell_types")).rename({"primary_type": "type", "additional_type(s)": "additional_types"})
        cells = neurons.join(types, on="root_id", how="left")
        if raw.has("classification"):
            cls = _csv(raw.path("classification")).rename({"super_class": "superclass", "sub_class": "subclass"})
            cells = cells.join(cls, on="root_id", how="left")
        if raw.has("names"):
            cells = cells.join(_csv(raw.path("names")).select("root_id", "name"), on="root_id", how="left")
        if raw.has("connectivity_tags"):
            tags = _csv(raw.path("connectivity_tags")).rename({"connectivity_tag": "connectivity_tags"})
            cells = cells.join(tags, on="root_id", how="left")
        return cells

    def type_extras(self, raw: RawDir, types: pl.DataFrame) -> pl.DataFrame | None:
        if not raw.has("visual_types"):
            return None
        vis = nullify_sentinels(_csv(raw.path("visual_types")).select("type", "family", "subsystem", "category"))
        out = vis.select("type").unique().sort("type")
        for col in ("family", "subsystem", "category"):
            out = out.join(_majority(vis, col), on="type", how="left")
        return out

    def columns(self, raw: RawDir, cells: pl.DataFrame) -> pl.DataFrame | None:
        if not raw.has("columns"):
            return None
        cols = _csv(raw.path("columns")).rename({"hemisphere": "side"})
        return cols.select(
            "root_id", "p", "q", "side",
            pl.col("column_id").cast(pl.UInt16), pl.col("x").cast(pl.Int16), pl.col("y").cast(pl.Int16),
        )

    # ---- synapses ---------------------------------------------------------

    @staticmethod
    def _root_id_columns(names: list[str]) -> tuple[str, str, int]:
        """Return (pre column, post column, additive prefix) from headers like ``pre_root_id_720575940``."""
        pre = next(c for c in names if c.startswith("pre_root_id"))
        post = next(c for c in names if c.startswith("post_root_id"))
        m = re.search(r"(\d+)$", pre)
        if m is None or not post.endswith(m.group(1)):
            raise ValueError(f"cannot parse root-id prefix from {pre!r}/{post!r}")
        prefix = m.group(1)
        return pre, post, int(prefix) * 10 ** (_ROOT_ID_DIGITS - len(prefix))

    def synapse_batches(self, raw: RawDir) -> Iterator[pl.DataFrame]:
        path = raw.path("synapses")
        with pa.OSFile(str(path), "rb") as f, pa.CompressedInputStream(f, "gzip") as stream:
            header = pcsv.open_csv(stream, read_options=pcsv.ReadOptions(block_size=1 << 16)).schema.names
        pre, post, add = self._root_id_columns(header)
        types = {pre: pa.int64(), post: pa.int64(), "ctr_x": pa.uint32(), "ctr_y": pa.uint32(), "ctr_z": pa.uint32(), "neuropil": pa.string()}
        with pa.OSFile(str(path), "rb") as f, pa.CompressedInputStream(f, "gzip") as stream:
            reader = pcsv.open_csv(
                stream,
                read_options=pcsv.ReadOptions(block_size=self.block_size),
                convert_options=pcsv.ConvertOptions(
                    include_columns=[pre, post, *_SYNAPSE_COLUMNS], column_types=types, strings_can_be_null=True
                ),
            )
            try:
                for batch in reader:
                    df = pl.from_arrow(batch)
                    yield df.select(
                        (pl.col(pre) + add).alias("pre_root_id"),
                        (pl.col(post) + add).alias("post_root_id"),
                        pl.col("ctr_x").alias("x_nm"),
                        pl.col("ctr_y").alias("y_nm"),
                        pl.col("ctr_z").alias("z_nm"),
                        pl.col("neuropil"),
                    )
            finally:
                reader.close()
